<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\back-image.jpg" />
    <None Remove="Images\Frame_15.bmp" />
    <None Remove="Images\key-icon.png" />
    <None Remove="Images\logo.png" />
    <None Remove="Images\user-icon.png" />
    <None Remove="Images\user.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Mo.BoolToVisibility" Version="1.0.0.1" />
    <PackageReference Include="NLog" Version="5.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiService\ApiService.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\FileProcessor\FileProcessor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\back-image.jpg" />
    <Resource Include="Images\Frame_15.bmp" />
    <Resource Include="Images\key-icon.png" />
    <Resource Include="Images\logo.png" />
    <Resource Include="Images\user-icon.png" />
    <Resource Include="Images\user.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Views\Data\AddDataWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Data\VehiculeDetailView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Data\DocumentDetailView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Data\SingleDataView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Data\DataView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Device\AddWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Device\DevicesView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Shared\" />
  </ItemGroup>
</Project>
